### ISSUE TITLE
FR9. Client can view menu

### ISSUE THREAD

**Issue by sepfeiffer** [WSU-4110/WFoodPantryMobileApp#10]
|FR9. Client can view menu |
|---|
|**Goal**: The user must be able to view the menu of items provided by the W Pantry |
**Stakeholders:** Clients|
| **Description:** The system, upon button click by the user, should pull up an up-to-date list of the items provided by W Pantry. This would ideally be a separate feature in the menu, as to let users pre-plan their order ahead of time |
| **Origin:** This is a basic function allowing the client to interface with the pantry as identified in the initial proposal. |
| **Version:** 1.0  |  
|**Date:** 01/29/2021  
|  **Priority:** 1 |

**Comment by cborys19** [comment]
Since the client can view the food pantry's stock in the order form's dropdown menus, it was judged that that satisfies this issue's requirements and allows it to be closed.
