### ISSUE TITLE
FR10. Client can view pantry contact information

### ISSUE THREAD

**Issue by sepfeiffer** [WSU-4110/WFoodPantryMobileApp#11]
|FR10. Client can view pantry contact information |
|---|
|**Goal**: The user must be able to view the Food Pantry’s contact information within the app.|
**Stakeholders:** Clients|
| **Description:**  The system, upon button click by the user, should pull up an up-to-date listing of the Pantry’s contact information. This feature would be available for use at any moment the user is not placing an order via the client intake form.|
| **Origin:** This is a basic function allowing the client to interface with the pantry as identified in the initial proposal. |
| **Version:** 1.0  |  
|**Date:** 01/29/2021  
|  **Priority:** 1 |

**Comment by ddfn** [comment]
contact information is now available navigating from the user main menu
