### ISSUE TITLE
FR13. Update the menu

### ISSUE THREAD

**Issue by sepfeiffer** [WSU-4110/WFoodPantryMobileApp#14]
|FR13. Update the menu |
|---|
|**Goal**: The Pantry must be able to update the current menu of available foods to maintain an up-to-date inventory for the user to browse|
**Stakeholders:** Clients, Pantry|
| **Description:**  The Pantry must be able to maintain and accurately update the menu from which the user may select food items from. This can be done in ways like adding new items and removing items that have run out of stock.|
| **Origin:** This is a basic function allowing the client to interface with the pantry as identified in the initial proposal. |
| **Version:** 1.0  |  
|**Date:** 01/29/2021  
|  **Priority:** 1 |

**Comment by cborys19** [comment]
menu update functionality added as of pull request #64
