### ISSUE TITLE
NR1. The system must be able to authenticate users securely (security)

### ISSUE THREAD

**Issue by sepfeiffer** [WSU-4110/WFoodPantryMobileApp#19]
|NR1.  The system must be able to authenticate users securely (security)|
|---|
|**Goal**: The app must provide security through an authentication system to limit the scope of the Client users to current Wayne State students.|
**Stakeholders:** All|
| **Description:** Access to the pantry services are limited to Wayne State students. Therefore validation is required at the very earliest stages to ensure folks outside their scope are not interfacing with the system.  security procedures must be in accordance with current Wayne State standards.  |
| **Origin:** This is a basic function allowing the client to interface with the pantry as identified in the initial proposal.|
| **Version:** 1.0  |  
|**Date:** 01/29/2021  
|  **Priority:** 1 |

**Comment by ddfn** [comment]
users of the app are able to enter their wayne state email and password credentials in order to sign up for access to their user profiles.  Staff/admins have read write access to authentication through firebase to manage profiles and manage user access. closing requirement.
