### ISSUE TITLE
NR3. System will accept button and text input from user (Usability)

### ISSUE THREAD

**Issue by sepfeiffer** [WSU-4110/WFoodPantryMobileApp#21]
|NR3.   System will accept button and text input from user (Usability)|
|---|
|**Goal**: The program should be able to accept button and text inputs from the app user
**Stakeholders:** Clients|
| **Description:**  Every function on the application that utilizes a button or a text input should be able to properly connect to the database attached to the app, and be able to use this information to process the inputs and forward the user to the proper page/function|
| **Origin:** This is a basic function allowing the client to interface with the pantry as identified in the initial proposal.|
| **Version:** 1.0  |  
|**Date:** 01/29/2021  
|  **Priority:** 1 |

**Comment by ddfn** [comment]
client has the ability to interface with the system through buttons, text fields, and dropdown menus to utilize the services of the app. System employs MVC architecture principals and each of the parts of the architecture are able to communicate at a basic level. Closing issue
