### ISSUE TITLE
NR5. System services should work during Pantry business hours, at minimum (Accessibility)

### ISSUE THREAD

**Issue by sepfeiffer** [WSU-4110/WFoodPantryMobileApp#23]
|NR5. System services should work during Pantry business hours, at minimum (Accessibility)  |
|---|
|**Goal**: Orders through the app must at least work during Pantry business hours, if not at all hours of the day
**Stakeholders:** All|
| **Description:**  When filing the client intake form via the application, all orders must be able to be received by the Food Pantry during their business hours. This is the bare minimum for the app to run and remain accessible to users.|
| **Origin:** This is a basic function allowing the client to interface with the pantry as identified in the initial proposal.|
| **Version:** 1.0  |  
|**Date:** 01/29/2021  
|  **Priority:** 1 |

**Comment by ddfn** [comment]
This requirement depends on access to the app features by users and the staff. both Types of users have access.  Continuous development ensures the services are available all hours of the day.
