### ISSUE TITLE
FR2. Login/User Authentication UI

### ISSUE THREAD

**Issue by sepfeiffer** [WSU-4110/WFoodPantryMobileApp#3]
|FR2. Login/User Authentication UI  |
|---|
|**Goal**: The Clients will have to establish they are Wayne State students in order to utilize the food pantry’s services. |
**Stakeholders:** Clients|
| **Description:** The Client shall be able to identify themselves as a Wayne State student. Clients will be able to enter both their Wayne ID username and password, while receiving validation for input data. Successful logins will proceed to the welcome/splash page whereas unsuccessful login attempts will be blocked from access.  |
| **Origin:** This is a basic function allowing the client to interface with the pantry as identified in the initial proposal. |
| **Version:** 1.0  |  
|**Date:** 01/29/2021  
|  **Priority:** 1 |

**Comment by ddfn** [comment]
user interfaces for logins for both user and staff are complete. I'm closing this issue.
