### ISSUE TITLE
FR3. Splash page UI

### ISSUE THREAD

**Issue by sepfeiffer** [WSU-4110/WFoodPantryMobileApp#4]
|FR3. Splash page UI |
|---|
|**Goal**: To greet the clients with their options to utilize the services of the pantry through a simply designed UI.|
**Stakeholders:** Clients|
| **Description:** The welcome page will display options relating to specific information and options to utilize the pantry’s services. The Client will have the option to select from a displayed menu leading to the functions of the app.  |
| **Origin:** This is a basic function allowing the client to interface with the pantry as identified in the initial proposal. |
| **Version:** 1.0  |  
|**Date:** 01/29/2021  
|  **Priority:** 1 |

**Comment by cborys19** [comment]
I'm going to attempt this FR today (2/25/21)

**Comment by cborys19** [comment]
splash screen has been added as of pull request #32
