### ISSUE TITLE
FR4. Clients can view "about" organization information page UI

### ISSUE THREAD

**Issue by sepfeiffer** [WSU-4110/WFoodPantryMobileApp#5]
|FR4.  Clients can view “about” organization information page UI.|
|---|
|**Goal**: The Client will be able to learn very basic facts about the W Food Pantry organization. |
**Stakeholders:** Clients|
| **Description:** The Client will have access to basic information about the W Food Pantry organization including. mission, goals, and history. This page will be accessible from the splash page and have the ability to conveniently return to the splash page.  |
| **Origin:** This is a basic function allowing the client to interface with the pantry as identified in the initial proposal. |
| **Version:** 1.0  |  
|**Date:** 01/29/2021  
|  **Priority:** 2 |

**Comment by cborys19** [comment]
I'm going to attempt this FR today (2/25/21)

**Comment by cborys19** [comment]
Issue addressed in pull request #38
