### ISSUE TITLE
FR8. Client can save order form

### ISSUE THREAD

**Issue by sepfeiffer** [WSU-4110/WFoodPantryMobileApp#9]
|FR8. Client can save order form |
|---|
|**Goal**: The user needs to be able to save their order for use in future orders |
**Stakeholders:** Clients|
| **Description:** The system should offer the customer a method to save their current order into the app, so they can submit an identical order in the future in the event of them wanting to place a similar order. |
| **Origin:** This is a basic function allowing the client to interface with the pantry as identified in the initial proposal. |
| **Version:** 1.0  |  
|**Date:** 01/29/2021  
|  **Priority:** 1 |

**Comment by jbucciero** [comment]
A defunct feature scrapped around Sprint 2 in terms of final features. The function to save order no longer required in the final build
